# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba3ba9413ff457f4c5e01f55adb31343329170067b57fecd74191d4e0cb90e8cc97670407ac4e484e08ff51e4a8a75aa2de3ec2d492f80c114126df12ff04c4

test:
  secret_key_base: ab6221b4a01aa6791c74bd92b8a7dd8995bfa7897b2c97490f3be922261cfce3937f55bb637d3c95460bcc809c293e79ca4546aa21b4db5e98e5886007cf8b77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
